
import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP
 */
public class Deber extends javax.swing.JFrame {

    /**
     * Creates new form Deber
     */
    public Deber() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblcambiar2 = new javax.swing.JLabel();
        lbltitulo = new javax.swing.JLabel();
        lblingrasar = new javax.swing.JLabel();
        txtoracion = new javax.swing.JTextField();
        lblcambiar = new javax.swing.JLabel();
        lblcambiar1 = new javax.swing.JLabel();
        btnvocalO = new javax.swing.JButton();
        btnvocalA = new javax.swing.JButton();
        btninvertir = new javax.swing.JButton();
        btnseparar = new javax.swing.JButton();

        lblcambiar2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbltitulo.setText("           ORACIONES");

        lblingrasar.setBackground(new java.awt.Color(153, 255, 153));
        lblingrasar.setText("INGRAR ORACION:");

        txtoracion.setBackground(new java.awt.Color(204, 204, 255));
        txtoracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtoracionActionPerformed(evt);
            }
        });

        lblcambiar1.setBackground(new java.awt.Color(255, 51, 255));

        btnvocalO.setBackground(new java.awt.Color(204, 255, 204));
        btnvocalO.setText("CAMBIAR VOCAL Oo");
        btnvocalO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvocalOActionPerformed(evt);
            }
        });

        btnvocalA.setBackground(new java.awt.Color(153, 255, 204));
        btnvocalA.setText("CAMBIAR VOCAL Aa");
        btnvocalA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvocalAActionPerformed(evt);
            }
        });

        btninvertir.setBackground(new java.awt.Color(255, 255, 204));
        btninvertir.setText("IMBERTIR ORACION");
        btninvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninvertirActionPerformed(evt);
            }
        });

        btnseparar.setBackground(new java.awt.Color(255, 204, 204));
        btnseparar.setText("SEPARAR");
        btnseparar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsepararActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblingrasar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnseparar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnvocalO)
                        .addGap(26, 26, 26)
                        .addComponent(btnvocalA)
                        .addGap(36, 36, 36)
                        .addComponent(btninvertir)
                        .addContainerGap(15, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtoracion, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                            .addComponent(lblcambiar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblcambiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbltitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(237, 237, 237))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lbltitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblingrasar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtoracion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblcambiar1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblcambiar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnvocalO)
                    .addComponent(btnvocalA)
                    .addComponent(btninvertir)
                    .addComponent(btnseparar))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtoracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtoracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtoracionActionPerformed

    private void btnvocalOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvocalOActionPerformed

        String vocalO = txtoracion.getText();
        //METODO PARA PODER REMPLAXZAR LAS VOCALES O POR EL SIMBOLO $
        //replaceAll se utiliza para poder remplazar 
      String resultado = vocalO.replaceAll("[Oo]", "\\$");

        lblcambiar1.setText("Palabras a remplazar: " + vocalO);
        lblcambiar.setText(" Remplazado " + resultado);
        
        
    }//GEN-LAST:event_btnvocalOActionPerformed

    private void btnvocalAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvocalAActionPerformed
        // TODO add your handling code here:
        
        String vocala = txtoracion.getText();
        //METODO PARA PODER REMPLAZAR TODAS LAS LETRAS A o a con el simbolo @
        //replaceAll se utiliza para poder remplazar 
      String resultado = vocala.replaceAll("[Aa]", "\\@");

        lblcambiar1.setText("Palabras a remplazar: " + vocala );
        
        lblcambiar.setText(" Remplazado " + resultado);
        
        
    }//GEN-LAST:event_btnvocalAActionPerformed

    private void btninvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninvertirActionPerformed
        
        
        String oracionOriginal = txtoracion.getText();
        //StringBuilder METODO QUE AYUDA A MODIFICAR UNA CADENA 
        StringBuilder oracionInvertida = new StringBuilder();

     for (int i = oracionOriginal.length() - 1; i >= 0; i--) {
         
         // AGREGAR CADA CARACTER AL STRINGBUILDER EN UN ORDEN INVERSO
         oracionInvertida.append(oracionOriginal.charAt(i));
         //APPEND SE UTILIZA PARA AGREGAR CARACTERES U OTROS TIPOS DE
         //DATOS AL FINAL DE LA SECUENCIA.
         }
  //PARA QUE ME IMPLIMA LAS PALABRAS QUE SE VAN A INVERTIR Y PARA
  //QUE YA ME SALGA IMPRESA LA ORACION INVERTIDA
    lblcambiar1.setText("Oración Original: " + oracionOriginal);
    lblcambiar.setText("Oración Invertida: " + oracionInvertida);

    }//GEN-LAST:event_btninvertirActionPerformed

    private void btnsepararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsepararActionPerformed
        // TODO add your handling code here:
        String oracion = txtoracion.getText();
        //METODO PARA DIVIDIR LA ORACION  CADA VEZ QUE ESTE UN ESPACIO EN BLANCO
        String[] palabras = oracion.split(" ");
        //EL SPLIT SE UTILIZA PARA PODER DIVIR UNA CADENA  EN PARTES MAS PEQUENIAS
        
       //PARA IMPRIMIR LA ORACION SEPARADA POR PARTES
            JOptionPane.showMessageDialog(null , palabras);
            
        
    }//GEN-LAST:event_btnsepararActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Deber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Deber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Deber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Deber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Deber().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btninvertir;
    private javax.swing.JButton btnseparar;
    private javax.swing.JButton btnvocalA;
    private javax.swing.JButton btnvocalO;
    private javax.swing.JLabel lblcambiar;
    private javax.swing.JLabel lblcambiar1;
    private javax.swing.JLabel lblcambiar2;
    private javax.swing.JLabel lblingrasar;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JTextField txtoracion;
    // End of variables declaration//GEN-END:variables
}
